apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: zipkin
spec:
  selector:
    app: zipkin
  ports:
    - protocol: TCP
      port: 9411            
      targetPort: 9411      
      nodePort: 30911       
  type: NodePort
