apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-service-monitor
  namespace:  rm-photo-app
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: user-service
  namespaceSelector:
    matchNames:
      - rm-photo-app
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
