version: '3.8'

services:

  # CONFIG SERVER 
  configsvr:
    image: mongo:6
    container_name: configsvr
    command: mongod --configsvr --replSet configReplSet --port 27017
    ports:
      - "27019:27017" 
    volumes:
      - ./mongo/configdb:/data/db
    networks:
      - mongo-cluster

  # SHARD 1 - REPLICA SET
  shard1a:
    image: mongo:6
    container_name: shard1a
    command: mongod --shardsvr --replSet shard1 --port 27017
    ports:
      - "27101:27017"
    volumes:
      - ./mongo/shard1a:/data/db
    networks:
      - mongo-cluster

  shard1b:
    image: mongo:6
    container_name: shard1b
    command: mongod --shardsvr --replSet shard1 --port 27017
    networks:
      - mongo-cluster

  shard1c:
    image: mongo:6
    container_name: shard1c
    command: mongod --shardsvr --replSet shard1 --port 27017
    networks:
      - mongo-cluster

  # SHARD 2 - REPLICA SET
  shard2a:
    image: mongo:6
    container_name: shard2a
    command: mongod --shardsvr --replSet shard2 --port 27017
    ports:
      - "27104:27017"
    volumes:
      - ./mongo/shard2a:/data/db
    networks:
      - mongo-cluster

  shard2b:
    image: mongo:6
    container_name: shard2b
    command: mongod --shardsvr --replSet shard2 --port 27017
    networks:
      - mongo-cluster

  shard2c:
    image: mongo:6
    container_name: shard2c
    command: mongod --shardsvr --replSet shard2 --port 27017
    networks:
      - mongo-cluster

  # MONGOS ROUTER 
  mongos:
    image: mongo:6
    container_name: mongos
    command: mongos --configdb configReplSet/configsvr:27017 --bind_ip_all
    ports:
      - "27017:27017" 
    depends_on:
      - configsvr
      - shard1a
      - shard1b
      - shard1c
      - shard2a
      - shard2b
      - shard2c
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
