apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  namespace: databases
spec:
  selector:
    app: mongos
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  type: ClusterIP
