apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: databases
spec:
  selector:
    app: minio
  ports:
    - name: api
      port: 9102
      targetPort: 9000
    - name: console
      port: 9101
      targetPort: 9001
  type: ClusterIP
