# minio-nodeport.yaml
apiVersion: v1
kind: Service
metadata:
  name: minio-public           
  namespace: databases
spec:
  type: NodePort
  selector:
    app: minio                   
  ports:
  
    - name: api
      port: 9000                
      targetPort: 9000          
      nodePort: 31002           
   
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 32001
