apiVersion: v1
kind: Service
metadata:
  name: shard2-service
  namespace: databases
spec:
  clusterIP: None
  selector:
    app: shard2
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
