apiVersion: v1
kind: Service
metadata:
  name: nginx-cdn-service
  namespace: databases
spec:
  type: NodePort
  selector:
    app: nginx-cdn
  ports:
    - name: http
      port: 8089
      targetPort: 80
      nodePort: 30021
