# elasticsearch-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: esdata-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/esdata"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esdata
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  
