# elasticsearch-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: databases
spec:
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
