version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: local-cdn
    ports:
      - "8089:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - shared-net

networks:
  shared-net:
    external: true
