# shard2-0
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shard2-pv-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/shard2-0"
    type: DirectoryOrCreate
  claimRef:
    name: shard2-storage-shard2-0
    namespace: databases
---
# shard2-1
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shard2-pv-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/shard2-1"
    type: DirectoryOrCreate
  claimRef:
    name: shard2-storage-shard2-1
    namespace: databases
---
# shard2-2
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shard2-pv-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/shard2-2"
    type: DirectoryOrCreate
  claimRef:
    name: shard2-storage-shard2-2
    namespace: databases
