# shard1-0
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shard1-pv-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/shard1-0"
    type: DirectoryOrCreate
  claimRef:
    name: shard1-storage-shard1-0
    namespace: databases
---
#  shard1-1
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shard1-pv-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/shard1-1"
    type: DirectoryOrCreate
  claimRef:
    name: shard1-storage-shard1-1
    namespace: databases
---
#  shard1-2
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shard1-pv-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/shard1-2"
    type: DirectoryOrCreate
  claimRef:
    name: shard1-storage-shard1-2
    namespace: databases
