apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-follow-pv
  namespace: databases
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongo-follow
