apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-follow-pv
  namespace: databases
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongo-follow"
    type: DirectoryOrCreate
