apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-follow
  namespace: databases
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-follow
  template:
    metadata:
      labels:
        app: mongo-follow
    spec:
      containers:
        - name: mongo
          image: 172.29.3.41:5000/mongo:6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-follow-pvc
