apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: rm-photo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway
          image: 172.29.3.41:5000/gateway-service:zipkin
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Dspring.zipkin.sender.type=webclient
                -Djdk.httpclient.allowRestrictedHeaders=connection
                -Dreactor.netty.http.http2=false

            
