apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: rm-photo-app
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
