version: "3.8"

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9102:9000" # API
      - "9101:9001" # Console UI
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - "./minio-data:/data"
    command: server /data --console-address ":9001"
    networks:
      - shared-net
networks:
  shared-net:
    name: shared-net
