apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  namespace: rm-photo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: 172.29.3.41:5000/post-service:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
