apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shard1
  namespace: databases
spec:
  serviceName: shard1-service
  replicas: 3
  selector:
    matchLabels:
      app: shard1
  template:
    metadata:
      labels:
        app: shard1
    spec:
      containers:
        - name: mongod
          image: 172.29.3.41:5000/mongo:6
          command:
            - mongod
            - "--shardsvr"
            - "--replSet"
            - "shard1ReplSet"
            - "--bind_ip_all"
            - "--port"
            - "27017"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: shard1-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: shard1-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: manual
        resources:
          requests:
            storage: 1Gi
