apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: rm-photo-app
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: 172.29.3.41:5000/auth-service:0.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Dspring.zipkin.sender.type=webclient
                -Djdk.httpclient.allowRestrictedHeaders=connection
                -Dreactor.netty.http.http2=false
          #resources:
            #requests:
              #cpu: "250m"
              #memory: "128Mi"
            #limits:
              #cpu: "600m"
              #memory: "512Mi"
