apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-service
  namespace: rm-photo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed-service
  template:
    metadata:
      labels:
        app: feed-service
    spec:
      containers:
        - name: feed-service
          image: 172.29.3.41:5000/feed-service:1.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: JAVA_TOOL_OPTIONS
              value: >-
               -Dspring.zipkin.sender.type=webclient
               -Djdk.httpclient.allowRestrictedHeaders=connection
               -Dreactor.netty.http.http2=false

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "700m"
              memory: "2Gi"
