apiVersion: apps/v1
kind: Deployment
metadata:
  name: follow-service
  namespace: rm-photo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: follow-service
  template:
    metadata:
      labels:
        app: follow-service
    spec:
      containers:
        - name: follow-service
          image: 172.29.3.41:5000/follow-service:1.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: JAVA_TOOL_OPTIONS
              value: >-
               -Dspring.zipkin.sender.type=webclient
               -Djdk.httpclient.allowRestrictedHeaders=connection
               -Dreactor.netty.http.http2=false
          #resources:
            #requests:
              #cpu: "250m"
              #memory: "200Mi"
            #limits:
              #cpu: "600m"
              #memory: "512Mi"
