apiVersion: apps/v1
kind: Deployment
metadata:
  name: follow-service
  namespace: photo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: follow-service
  template:
    metadata:
      labels:
        app: follow-service
    spec:
      containers:
        - name: follow-service
          image: 172.29.3.41:5000/follow-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
