apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: post-service-vpa
  namespace: rm-photo-app
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: post-service
  updatePolicy:
    updateMode: "Auto"  
  resourcePolicy:
    containerPolicies:
      - containerName: "post-service"
        controlledValues: "RequestsOnly"
        minAllowed:
          memory: "1250Mi"
        maxAllowed:
          memory: "3Gi"
          
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: post-service-pdb
  namespace: rm-photo-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: post-service

