apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  namespace: rm-photo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: 172.29.3.41:5000/post-service:1.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: JAVA_TOOL_OPTIONS
              value: >-
               -Dspring.zipkin.sender.type=webclient
               -Djdk.httpclient.allowRestrictedHeaders=connection
               -Dreactor.netty.http.http2=false
          resources:
            requests:
              cpu: "100m"
              memory: "1250Mi"
            limits:
              cpu: "500m"
              memory: "2Gi"
