apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: rm-photo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: 172.29.3.41:5000/user-service:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Dspring.zipkin.sender.type=webclient
                -Djdk.httpclient.allowRestrictedHeaders=connection
                -Dreactor.netty.http.http2=false
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
