apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: rm-photo-app
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: ClusterIP
