apiVersion: v1
kind: Service
metadata:
  name: feed-service
  namespace: rm-photo-app
  labels:
    app: feed-service
spec:
  type: NodePort
  selector:
    app: feed-service
  ports:
    - name: http
      protocol: TCP
      port: 8085          # ??? ?? ???? ?????? ???? ????????
      targetPort: 8085    # ??? ?? ???? ???????
      nodePort: 30085 
      
