apiVersion: v1
kind: Service
metadata:
  name: follow-service
  namespace: rm-photo-app
  labels:
    app: follow-service
spec:
  selector:
    app: follow-service
  ports:
    - name: http
      protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP