apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: photo-app
  labels:
    app: search-service
spec:
  selector:
    app: search-service
  ports:
    - protocol: TCP
      port: 8081         
      targetPort: 8081   
