apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: rm-photo-app
  labels:
    app: search-service
spec:
  selector:
    app: search-service
  ports:
    - name: http
      protocol: TCP
      port: 8081         
      targetPort: 8081 
  type: ClusterIP  
